// LOAD
export const LOAD_PRODUCT_SUCCESS = "LOAD_PRODUCT_SUCCESS"
export const LOAD_PRODUCT_FAILURE = "LOAD_PRODUCT_FAILURE"

// LOAD DETAIL
export const LOAD_DETAIL_SUCCESS = "LOAD_DETAIL_SUCCESS"
export const LOAD_DETAIL_FAILURE = "LOAD_DETAIL_FAILURE"

// ADD DATA
export const ADD_DATA = "ADD_DATA"
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS"
export const ADD_DATA_FAILURE = "ADD_DATA_FAILURE"

// VOTE
export const ADD_VOTE = "ADD_VOTE"
export const ADD_VOTE_SUCCESS = "ADD_VOTE_SUCCESS"
export const ADD_VOTE_FAILURE = "ADD_VOTE_FAILURE"

// RATE
export const ADD_RATE = "ADD_RATE"
export const ADD_RATE_SUCCESS = "ADD_RATE_SUCCESS"
export const ADD_RATE_FAILURE = "ADD_RATE_FAILURE"


